### ISSUE TITLE
Stock reaction continuous deployment target

### ISSUE THREAD

**Issue by focusaurus** [reactioncommerce/reaction-feature-requests#102]
We'd like to set up continuous deployment of a stock reaction system. Ideally this would be an Internet-facing site. Useful for demo purposes, testing, dogfooding, grabbing screenshots, etc.

**Comment by machikoyasuda** [comment]
Duplicate (more or less) of https://github.com/reactioncommerce/reaction-feature-requests/issues/58

**Comment by griggheo** [comment]
I am working with @jeffcorpuz on the infrastructure side of things. As architected currently, we are going to use Pulumi (with real TypeScript code) to launch a Kubernetes cluster using AWS EKS. We'll install all necessary services inside that cluster (including MongoDB).

**Comment by focusaurus** [comment]
OK closing as duplicate of #58
