### ISSUE TITLE
Upgrade Hydra to oryd/hydra:v1.0.0

### ISSUE THREAD

**Issue by RStrydom** [reactioncommerce/reaction-feature-requests#112]
Hi :smile: ,

In order to take advantage of the stable release of Hydra, we would like to use the latest version as of this writing which is v1.0.0.

When you upgrade to version 1 the Hydra API calls are not the same anymore and challenges now need to be passed as a query parameters
more information about the fixes applied after the currently used beta version can be found here:
https://github.com/ory/hydra/blob/master/CHANGELOG.md#v100-2019-06-24
https://www.ory.sh/docs/hydra/oauth2

We have already forked and started fixing up the reaction and example storefront repos and will make a group of pull requests to address it and bump the hydra image version in reaction-hydra :+1:

**Comment by loan-laux** [comment]
@RStrydom would you mind closing this issue?
