### ISSUE TITLE
Needs Documentation for Project setup without docker or a buildscript

### ISSUE THREAD

**Issue by ARKKYN** [reactioncommerce/reaction-feature-requests#115]
Please add a section in documentation to setup project without docker

**Comment by focusaurus** [comment]
A non-docker setup is complex and adds a very large amount of variability which makes documentation difficult to write and follow. The consistency we get through docker is what enables us to document the process and keep it accurate across releases. Documenting a direct host installation without docker would be a long list of links to third party installation articles for various databases, prerequisites, utilities, etc. This is not something we have on our product roadmap at this time.

**Comment by rawsp33d** [comment]
I agree with what @focusaurus said in terms of whether to document such things. But I also want to be clear we are certainly not discouraging running outside of docker. It is very possible and not overly difficult to get everything running outside of docker. I don't think we should clutter our docs with the specifics but essentially you can look at the commands used in the docker and docker compose files. Depending on the specific service you may have to change some `.env` config settings as well.

People that want to go passed the documented boundaries should find little trouble with this process specifically. I have at various points run most of our services outside of docker, as have many others, and didn't encounter all that much turbulence. At the end of the day it's more that we want to focus our docs on something universal and not have to worry about supporting infinite system/platform permutations.

Thank you for the suggestion, and keep 'em coming!
