### ISSUE TITLE
microservices

### ISSUE THREAD

**Issue by ARKKYN** [reactioncommerce/reaction-feature-requests#116]
Please split it into microservices

**Comment by focusaurus** [comment]
This process is underway but it's a multi-major-release process and too big to track as a feature request in a useful way. In Reaction 2.0 we separated the storefront into its own service. In 3.0 we'll be splitting the nodejs api server into a separate service from the admin service. We also have plans to split out the identity service from the admin service. It is in line with our architecture roadmap so we're working on it but each new service is likely to appear in a major release of reaction.
