### ISSUE TITLE
Going monorepo @reactioncommerce

### ISSUE THREAD

**Issue by agustif** [reactioncommerce/reaction-feature-requests#122]
I just saw this: https://github.com/reactioncommerce/reaction-hydra/issues/36

What about going monorepo and renaming all /packages/ to @reactioncommerce/platform etc

**Comment by agustif** [comment]
I was a little short on words yesterday opening the issue.

I think this move, using standard tooling for it like lerna, yarn workspaces, and such, could greatly help the discoverability of all the projects when diving into the codebase, and also help them being in synchronicity on same release v.2.9.0 for example (instead of keeping that in sync manually).

Also would be good for the testing suit to be passed on all PR/merge/commits and see if tests fails before catastrophe

Anyway, I think it would be a great move to unify and renew with the v3 launch, no meteor backend to keep in a separate repo now!

**Comment by agustif** [comment]
It was hard for me for example to find out about reactioncommerce/proxy-traefik to handle my deployment to a DO droplet with docker-compose.

**Comment by agustif** [comment]
I've found this repo/guide and has helped a lot, https://github.com/reactioncommerce/proxy-traefik/blob/master/docs/SimpleDeploymentGuide.md

I still have trouble with my hydra-client

**Comment by focusaurus** [comment]
We don't have any near-term plans to convert to a monorepo so I would not anticipate any changes here soon. Just to set your expectations. It would be a major project and I think the chances of it bubbling to the top of our priorities are very low. All of the benefits listed above have counterarguments but I'm not sure it would be productive to go through them in this issue.

**Comment by agustif** [comment]
Kay, no problem, this can be closed for now then I guess
