### ISSUE TITLE
Hyperlocal Marketplace Support

### ISSUE THREAD

**Issue by birender-s** [reactioncommerce/reaction-feature-requests#131]
I am actually looking for Hyperlocal Marketplace feature exposed via REST APIs to be consumed by custom native mobie Apps (Android, iOS) allowing:

1. **Sellers** to register through App and post product(s) by providing details like Product category, name, quantity, service location radius (Lat/long, distance e.g. 10 KM/Miles area).

1. **Buyer** to get a list of products available in nearby area (customizable via Lat/Long/radius). Receive notifications about new/updated products.

These features mean that the APIs and associated services (PUSH notifications/webhooks/events...) are supported by the backend.
As per [this thread ](https://github.com/reactioncommerce/reaction-admin/issues/93)and [Admin UI access control change](https://github.com/reactioncommerce/api-plugin-accounts/pull/17), looks like Reaction platform now supports adding and managing Shops via REST APIs (UI might not be ready though).
I need your confirmation and advise on achieving above mentined Hyperlocal Marketplace capability. UI development is not critical for me since custom mobile App UI should cover that but I need APIs and other backend capabilities e.g. webhooks/events/PUSH notifications...
Please note that I came across Reaction platform recently and yet to deep dive doc/technical specs. Thanks in advance !

**Comment by birender-s** [comment]
gentle reminder !

**Comment by focusaurus** [comment]
Reaction commerce's API is GraphQL so we will not be providing any REST APIs.

Reaction Commerce is a plugin system for extensibility. That said, marketplace functionality is something we have approached in the past but the additional technical complexity would make it a major undertaking and it's not on any near-term roadmap.

**Comment by birender-s** [comment]
hi @focusaurus , thanks for sharing feedback !
Yes, i later understood about reaction's usage of GraphQL instead of REST. Loan Laux shared in separate discussion about few recent changes done by him and fellow members regarding multi-shop implementation but not a true multi-tenant marketplace. So i understand that some foundational work has started in this direction but still a significant set of development is required. Thanks once again !
