### ISSUE TITLE
Create Shop and Product Ratings Schema

### ISSUE THREAD

**Issue by hfmw** [reactioncommerce/reaction-feature-requests#32]
These must be on the horizon, as all marketplaces require these features? 

I have created a shop-ratings method for myself. However, it would be great if you could specify your schema design in advance, such that I can align my schema. This will prevent the requirements for data-migration.

**Comment by brent-hoover** [comment]
@willmoss1000 I do not foresee us every including this in the core product, this would probably be implemented as a separate/add-on package.

**Comment by hfmw** [comment]
Ok good to know. If you've not started this then no-worries. I'll just use my own package.

Thanks

**Comment by brent-hoover** [comment]
Closing. `wont-fix`
