### ISSUE TITLE
Set Default Shop Route to Products Template

### ISSUE THREAD

**Issue by hfmw** [reactioncommerce/reaction-feature-requests#35]
**Feature:**
I believe the shop route: "/shop/:shopSlug" should be set to the products template by default, rather than to match the index template?

Perhaps this is as issue rather than a feature request?

**Method:**
This would be very easily changeable in imports/plugins/core/router/lib/router.js. Link here: https://github.com/reactioncommerce/reaction/blob/766c97ebfacec67afecedb021cb3bac79658d1f1/imports/plugins/core/router/lib/router.js#L592

*I am already doing this myself in my build and can verify it works

**Comment by brent-hoover** [comment]
@willmoss1000 I would disagree. The idea behind the shop slug route would be that it goes to the shops "home page"

This is essentially a customization you want so I would not qualify this as a feature request or an issue.

**Comment by hfmw** [comment]
@zenweasel agreed, shops should have their own template by default. But currently there is no default shops "home page" template.

Not much value in this, will close.
