### ISSUE TITLE
Update React to 16.3

### ISSUE THREAD

**Issue by loanlaux** [reactioncommerce/reaction-feature-requests#41]
The React team released [version 16.3](https://github.com/facebook/react/releases/tag/v16.3.0) a couple days ago.

This new version (featuring a new Context API) will undoubtedly be useful to lots of developers working on Reaction projects.

On a related note, separation of the client and back-end means no more Meteor session variables. As they are often used as global reactive variables, leveraging the Context API to replace them makes a lot of sense to me. Less magic - better maintainability. 😀

There are no breaking changes announced for this version.

**Comment by loanlaux** [comment]
Any update on this?

**Comment by machikoyasuda** [comment]
React is now updated to 16.8.3: https://github.com/reactioncommerce/reaction/blob/v2.7.0/package.json#L109
