### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by DavidRouyer** [reactioncommerce/reaction-feature-requests#43]
The EU General Data Protection Regulation https://www.eugdpr.org/ compliance will be required for companies doing business in the EU starting May 25th, is Reaction compliant?

**Comment by loanlaux** [comment]
I have clients asking me about GDPR compliance. Can someone at Reaction confirm that RC is compliant? Would love to see an official statement on the website I can direct clients to, for example.

**Comment by machikoyasuda** [comment]
Hi @DavidRouyer, @loanlaux - Here's Reaction Commerce's GDPR FAQ page: https://www.reactioncommerce.com/legal/gdpr
