### ISSUE TITLE
Preserve and display newlines in Product Description

### ISSUE THREAD

**Issue by rotexhawk** [reactioncommerce/reaction-feature-requests#74]
It will be nice if we could add simple html tags like (`<br>`, `<li>`, `<p>` .etc) for product description, or maybe if the description field could just honor the spacing. 

Currently it removes all the spaces and converts the text into a simple string. Thank you.

**Comment by aldeed** [comment]
Closing as a storefront UI concern which people can implement by parsing descriptions as they see fit.

**Comment by brent-hoover** [comment]
Actually this had to do with it stripping newlines when saving, so you could never reparse those out. Not sure if it still does this.

**Comment by aldeed** [comment]
Nothing on the API does, unless the admin client still does. If anyone confirms it's still happening, feel free to open an issue in whichever repo the code doing the stripping lives.
