### ISSUE TITLE
Set default permissions for invited users

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-feature-requests#75]
Marketplace, Shop and Affiliate owners should be able to edit the permissions for any group associated with their shop or marketplace. E.g. maybe you don't want shop owners to be able to create tags, should be able to remove that from the default shop owner permission set.

For shop / affiliate owners - they should be able to customize what permissions are granted by default when they invite another person to help them administer their shop.

When the permissions of a group change, any user that has that permission group should also have their permissions changed to match the updated group permissions as well. Users who have a custom set of permissions that originally started with a group permission should not have their permissions altered.

**Comment by aldeed** [comment]
Resolved in 3.0+
