### ISSUE TITLE
Refund shipping for an order

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction-feature-requests#91]
A user with orders permissions should be able to refund shipping for an order.

Refunding the shipping for an order should update the order status as Shipping Refunded.

Refunding the order should trigger an Order Refunded event.

The Order Refunded event should send an email to the customer informing them of the refund having been initiated and add a notification to their notification list.

**Comment by aldeed** [comment]
Resolved in that any amount may be refunded
